steps:
  - label: "Before"
    command: |
      cat Readme.md
  - label: "Install python"
    command: apt-get update && apt-get install -y python3
  - label: "Run Test file"
    command: python3 test.py
  # - label: "PR Label Run"
  #   if: build.pull_request.labels='label_added'
  #   command: echo "Hey PR is labelled"
    
  # - input: "Information please"
  #   key: "info"
  #   fields:
  #     - text: "Type anything"
  #       key: "anything"
  # - label: "After"
  #   depends_on: "info"
  #   command: |
  #     git pull origin main
  #     cat Readme.md
