steps:
  - label: "Before"
    command: |
      cat Readme.md
  - input: "Information please"
    key: "info"
    fields:
      - text: "Type anything"
        key: "anything"
  - label: "After"
    depends_on: "info"
    command: |
      cat Readme.md
