steps:
  - label: "Before"
    command: |
      cat Readme.md
  - command: "npm start"
    plugins:
      - docker#v5.9.0:
          image: "node:7"
          always-pull: true
          mount-checkout: false
  - input: "Information please"
    key: "info"
    fields:
      - text: "Type anything"
        key: "anything"
  - label: "After"
    depends_on: "info"
    command: |
      git pull origin main
      cat Readme.md
