steps:
  - label: ":hammer: Example Script"
    command: "script1.sh"

  - input: "Information please"
    key: "info"
    fields:
      - text: "Type anything"
        key: "anything"
        format: ^0\.0\.\d+$

  - label: "Output"
    depends_on: "info"
    command: echo $(buildkite-agent meta-data get anything)
