steps:
  - label: "Before"
    command: |
      cat Readme.md
  - command: |
      apt-get update && apt-get install -y python3
      python3 test.py
    plugins:
      - docker#v5.10.0:
          image: "docker:latest"
          always-pull: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
  # - label: "PR Label Run"
  #   if: build.pull_request.labels='label_added'
  #   command: echo "Hey PR is labelled"
    
  # - input: "Information please"
  #   key: "info"
  #   fields:
  #     - text: "Type anything"
  #       key: "anything"
  # - label: "After"
  #   depends_on: "info"
  #   command: |
  #     git pull origin main
  #     cat Readme.md
