steps:
  - label: "Before"
    command: |
      cat Readme.md
  - command: ls
    plugins:
      - docker#v3.3.0:
          image: node
  - input: "Information please"
    key: "info"
    fields:
      - text: "Type anything"
        key: "anything"
  - label: "After"
    depends_on: "info"
    command: |
      git pull origin main
      cat Readme.md
